### PR TITLE
support uglify

### PR DESCRIPTION
**Pull request by charlierudolph**
@AndreasMadsen

### CODE REVIEW

**Comment by charlierudolph** [comment]
@AndreasMadsen any thoughts?

**Comment by AndreasMadsen** [comment]
Sorry for not responding. But did you see my comment in #5

> That sounds like an issue with uglify not stack-chain. Try and browserify before uglify, then the return statement should be inside a function.

**Comment by charlierudolph** [comment]
Yeah I saw the comment. It is possible to uglify after browserifying but most things suggest uglifying before for better results. I think the PR cleans things up anyway as the duplicate checking is moved to its own file

**Comment by AndreasMadsen** [comment]
Alright. If you add a test case then I will take this.

I'm curious, in what context is this used i the browser?

**Comment by charlierudolph** [comment]
Its a dependency of [cucumber-js](https://github.com/cucumber/cucumber-js) used to filter the stack traces. And is being browserfied so cucumber-js can be run in the browser. 

I don't actually know how to add a test case for this, aside from just uglifying it and checking that it doesn't error. Would you be okay with a test like that?

Just googling "javascript return outside function", you see a lot of examples of where having a return statement outside of a function caused errors.

**Comment by charlierudolph** [comment]
Just discovered uglify actually has a CLI option to not error on return statements outside of functions but the current javascript API doesn't allow me access.

**Comment by AndreasMadsen** [comment]
> I don't actually know how to add a test case for this, aside from just uglifying it and checking that it doesn't error. Would you be okay with a test like that?

That would be fine.

> Just googling "javascript return outside function", you see a lot of examples of where having a return statement outside of a function caused errors.

The reason why it works here is because node wraps all files in a function (see https://github.com/nodejs/node/blob/master/src/node.js#L942L945). Thus in a node context having a return _not inside a function_ is okay, though not something you see often.

**Comment by charlierudolph** [comment]
@AndreasMadsen test added

**Comment by AndreasMadsen** [comment]
Looks good. Thanks

**Comment by AndreasMadsen** [comment]
Version 1.3.4 is now published.

**Comment by charlierudolph** [comment]
Awesome. Thanks

**Pull request merged**
